default["mo_backup_sample"]["id"] = "my_app"
default["mo_backup_sample"]["description"] = "My app"
default["mo_backup_sample"]["user"] = "vagrant"
default["mo_backup_sample"]["databag"] = "applications"
default["mo_backup_sample"]["backup"]["storages_databag"] = "backup_storages"
default["mo_backup_sample"]["backup"]["mail_databag"] = "mail_databag"
